#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="db_business")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_businessConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<职工> 职工
	{
		get
		{
			return this.GetTable<职工>();
		}
	}
}

[Table(Name="dbo.职工")]
public partial class 职工
{
	
	private int _职工ID;
	
	private string _职工号;
	
	private string _仓库号;
	
	private string _姓名;
	
	private string _性别;
	
	private System.Nullable<int> _工资;
	
	public 职工()
	{
	}
	
	[Column(Storage="_职工ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int 职工ID
	{
		get
		{
			return this._职工ID;
		}
		set
		{
			if ((this._职工ID != value))
			{
				this._职工ID = value;
			}
		}
	}
	
	[Column(Storage="_职工号", DbType="VarChar(50)")]
	public string 职工号
	{
		get
		{
			return this._职工号;
		}
		set
		{
			if ((this._职工号 != value))
			{
				this._职工号 = value;
			}
		}
	}
	
	[Column(Storage="_仓库号", DbType="VarChar(50)")]
	public string 仓库号
	{
		get
		{
			return this._仓库号;
		}
		set
		{
			if ((this._仓库号 != value))
			{
				this._仓库号 = value;
			}
		}
	}
	
	[Column(Storage="_姓名", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string 姓名
	{
		get
		{
			return this._姓名;
		}
		set
		{
			if ((this._姓名 != value))
			{
				this._姓名 = value;
			}
		}
	}
	
	[Column(Storage="_性别", DbType="VarChar(10)")]
	public string 性别
	{
		get
		{
			return this._性别;
		}
		set
		{
			if ((this._性别 != value))
			{
				this._性别 = value;
			}
		}
	}
	
	[Column(Storage="_工资", DbType="Int")]
	public System.Nullable<int> 工资
	{
		get
		{
			return this._工资;
		}
		set
		{
			if ((this._工资 != value))
			{
				this._工资 = value;
			}
		}
	}
}
#pragma warning restore 1591
